version: 0.2

phases:
  pre_build:
    commands:
      - set -e
      - sh $CODEBUILD_SRC_DIR/tests/preflight.sh
      - mkdir -p $CODEBUILD_SRC_DIR/tests/shared_resources
      - TAG=`git describe --tags $(git rev-list --tags --max-count=1)`
      - cd $CODEBUILD_SRC_DIR/tests/shared_resources && wget -nv https://mondriantestdata.s3.amazonaws.com/mondrian-ref-20-22.tar.gz && tar -xvf mondrian-ref-20-22.tar.gz
      - cd $CODEBUILD_SRC_DIR/tests/shared_resources && wget -qO- https://get.nextflow.io | bash
      - cd $CODEBUILD_SRC_DIR/docker && sh build.sh alignment $QUAY_USR $QUAY_PSW Y
      - cd $CODEBUILD_SRC_DIR/docker && sh build.sh hmmcopy $QUAY_USR $QUAY_PSW Y
      - cd $CODEBUILD_SRC_DIR/docker && sh build.sh breakpoint_calling $QUAY_USR $QUAY_PSW Y
      - cd $CODEBUILD_SRC_DIR/docker && sh build.sh variant_calling $QUAY_USR $QUAY_PSW Y
      - cd $CODEBUILD_SRC_DIR/docker && sh build.sh haplotype_calling $QUAY_USR $QUAY_PSW Y
  build:
    commands:
      - sh $CODEBUILD_SRC_DIR/tests/test.sh $CODEBUILD_SRC_DIR/tests $CODEBUILD_SRC_DIR/tests/shared_resources qc qc qc
