FROM quay.io/singlecellpipelinetest/miniconda3:4.12.0
ARG VERSION

RUN pip install git+https://github.com/mondrian-scwgs/mondrian_utils.git@$VERSION
RUN pip install git+https://github.com/mondrian-scwgs/csverve.git@v0.3.7
RUN pip install matplotlib seaborn scikit-learn statsmodels ete3

