FROM quay.io/singlecellpipelinetest/miniconda3:4.12.0
ADD . /app

RUN apt-get update && apt-get install -y libltdl7 parallel && rm -rf /var/lib/apt/lists/*

RUN conda install --file /app/align_requirements.yml

RUN pip install git+https://github.com/mondrian-scwgs/mondrian_utils.git@v0.0.92
RUN pip install git+https://github.com/mondrian-scwgs/csverve.git@v0.3.7
RUN pip install matplotlib==3.5.3 seaborn scikit-learn statsmodels
RUN pip install git+https://github.com/shahcompbio/cell_cycle_classifier.git@v0.0.4
RUN pip install tables jinja2 statsmodels pypdf2


RUN conda create --name trimgalore
SHELL ["conda", "run", "-n", "trimgalore", "/bin/bash", "-c"]
RUN conda install --file /app/trimgalore_requirements.yml
RUN wget https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org%2Fpackages%2F3.6%2Fbioc%2Fsrc%2Fcontrib%2FArchive%2FATACseqQC%2FATACseqQC_1.2.6.tar.gz && R CMD INSTALL archive.bioconductor.org%2Fpackages%2F3.6%2Fbioc%2Fsrc%2Fcontrib%2FArchive%2FATACseqQC%2FATACseqQC_1.2.6.tar.gz && rm archive.bioconductor.org%2Fpackages%2F3.6%2Fbioc%2Fsrc%2Fcontrib%2FArchive%2FATACseqQC%2FATACseqQC_1.2.6.tar.gz
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]
ENV PATH="${PATH}:/opt/conda/envs/trimgalore/bin"

RUN conda create --name igvtools
SHELL ["conda", "run", "-n", "igvtools", "/bin/bash", "-c"]
RUN conda install --file /app/igvtools_requirements.yml
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]
ENV PATH="${PATH}:/opt/conda/envs/igvtools/bin"
